# Generated by Django 4.2.30 on 2026-04-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('celular', models.CharField(max_length=16, verbose_name='Celular')),
                ('telefone', models.CharField(blank=True, default='', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, default='', max_length=255, verbose_name='Complemento')),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas/', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PacienteAnamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_tratamento_medico', models.BooleanField(default=False, verbose_name='Está em tratamento médico atualmente?')),
                ('em_tratamento_medico_obs', models.TextField(blank=True, default='', verbose_name='Qual médico / tratamento?')),
                ('usa_medicamento', models.BooleanField(default=False, verbose_name='Faz uso de algum medicamento regularmente?')),
                ('usa_medicamento_obs', models.TextField(blank=True, default='', verbose_name='Qual(is) medicamento(s)?')),
                ('alergia_medicamento', models.BooleanField(default=False, verbose_name='Tem alergia a algum medicamento ou substância?')),
                ('alergia_medicamento_obs', models.TextField(blank=True, default='', verbose_name='Qual(is) alergia(s)?')),
                ('diabetico', models.BooleanField(default=False, verbose_name='É diabético(a)?')),
                ('hipertensao', models.BooleanField(default=False, verbose_name='Tem pressão alta (hipertensão)?')),
                ('hipotensao', models.BooleanField(default=False, verbose_name='Tem pressão baixa (hipotensão)?')),
                ('problema_cardiaco', models.BooleanField(default=False, verbose_name='Tem algum problema cardíaco?')),
                ('problema_cardiaco_obs', models.TextField(blank=True, default='', verbose_name='Qual problema cardíaco?')),
                ('problema_respiratorio', models.BooleanField(default=False, verbose_name='Tem algum problema respiratório? (asma, bronquite, rinite…)')),
                ('problema_respiratorio_obs', models.TextField(blank=True, default='', verbose_name='Qual problema respiratório?')),
                ('hepatite', models.BooleanField(default=False, verbose_name='Já teve hepatite ou doença hepática?')),
                ('hepatite_obs', models.TextField(blank=True, default='', verbose_name='Qual hepatite / doença hepática?')),
                ('problema_renal', models.BooleanField(default=False, verbose_name='Tem algum problema nos rins?')),
                ('hiv', models.BooleanField(default=False, verbose_name='É portador(a) de HIV/AIDS?')),
                ('epilepsia', models.BooleanField(default=False, verbose_name='Tem epilepsia ou convulsões?')),
                ('disturbio_coagulacao', models.BooleanField(default=False, verbose_name='Tem distúrbio de coagulação ou sangramento excessivo?')),
                ('osteoporose', models.BooleanField(default=False, verbose_name='Tem osteoporose ou outro problema ósseo?')),
                ('gravida', models.BooleanField(default=False, verbose_name='Está grávida ou suspeita de gravidez?')),
                ('amamentando', models.BooleanField(default=False, verbose_name='Está amamentando?')),
                ('fumante', models.BooleanField(default=False, verbose_name='É fumante?')),
                ('fumante_obs', models.CharField(blank=True, default='', max_length=100, verbose_name='Quantidade por dia?')),
                ('alcool', models.BooleanField(default=False, verbose_name='Consome bebida alcoólica?')),
                ('alcool_obs', models.CharField(blank=True, default='', max_length=100, verbose_name='Com que frequência?')),
                ('historico_cirurgias', models.BooleanField(default=False, verbose_name='Já realizou alguma cirurgia?')),
                ('historico_cirurgias_obs', models.TextField(blank=True, default='', verbose_name='Qual(is) cirurgia(s)?')),
                ('historico_internacoes', models.BooleanField(default=False, verbose_name='Já foi internado(a)?')),
                ('historico_internacoes_obs', models.TextField(blank=True, default='', verbose_name='Motivo da internação?')),
                ('doenca_pele', models.BooleanField(default=False, verbose_name='Tem alguma doença de pele ou dificuldade de cicatrização?')),
                ('doenca_pele_obs', models.TextField(blank=True, default='', verbose_name='Qual doença / dificuldade?')),
                ('queixa_principal', models.TextField(blank=True, default='', verbose_name='Queixa principal')),
                ('observacoes_gerais', models.TextField(blank=True, default='', verbose_name='Observações gerais')),
                ('data_anamnese', models.DateField(auto_now_add=True, verbose_name='Data da Anamnese')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='api.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Anamnese do Paciente',
                'verbose_name_plural': 'Anamneses dos Pacientes',
                'db_table': 'paciente_anamnese',
                'ordering': ['-data_anamnese'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Login')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='api.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Login da Empresa',
                'verbose_name_plural': 'Logins das Empresas',
                'db_table': 'empresa_login',
            },
        ),
    ]
