# Generated by Django 4.2.30 on 2026-04-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteanamnese',
            name='fumante_obs',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Quantidade de cigarros por dia?'),
        ),
    ]
