# Generated by Django 4.2.30 on 2026-04-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pacienteanamnese_fumante_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteExameClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_geral', models.TextField(blank=True, default='', verbose_name='Estado Geral')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura (m)')),
                ('pulso', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Pulso (bpm)')),
                ('frequencia_cardiaca', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Frequência Cardíaca (bpm)')),
                ('data_exame', models.DateField(auto_now_add=True, verbose_name='Data do Exame')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_clinicos', to='api.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Exame Clínico do Paciente',
                'verbose_name_plural': 'Exames Clínicos dos Pacientes',
                'db_table': 'paciente_exame_clinico',
                'ordering': ['-data_exame'],
            },
        ),
    ]
