# Generated by Django 4.2.30 on 2026-04-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_paciente_bairro_alter_paciente_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentesExameClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente_numero', models.IntegerField(verbose_name='Número do Dente')),
                ('dente_posicao', models.CharField(max_length=50, verbose_name='Posição do Dente')),
                ('dente_descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('exame_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentes', to='api.pacienteexameclinico', verbose_name='Exame Clínico')),
            ],
            options={
                'verbose_name': 'Dente do Exame Clínico',
                'verbose_name_plural': 'Dentes do Exame Clínico',
                'db_table': 'dentes_exame_clinico',
                'ordering': ['dente_numero', 'dente_posicao'],
                'unique_together': {('exame_clinico', 'dente_numero', 'dente_posicao')},
            },
        ),
    ]
