# Generated by Django 4.2.30 on 2026-04-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dentesexameclinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentesexameclinico',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Removido (soft-delete)'),
        ),
    ]
