# Generated by Django 4.2.30 on 2026-04-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dentesexameclinico_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='api.empresa'),
        ),
    ]
