# Generated by Django 4.2.30 on 2026-04-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_paciente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='empresa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='api.empresa'),
        ),
    ]
