# Generated by Django 4.2.30 on 2026-05-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dentesexameclinicoposexame'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='classificacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classificação'),
        ),
    ]
