# Generated by Django 6.0.5 on 2026-05-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_paciente_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.TextField(blank=True, null=True, verbose_name='Logo Base64'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='classificacao',
            field=models.IntegerField(default=999, verbose_name='Classificação'),
            preserve_default=False,
        ),
    ]
